// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjO4x9otPFVZYnBpGZuIIAKdfLlc_aOew',
    appId: '1:413834253790:web:a765af886ca631a129f94f',
    messagingSenderId: '413834253790',
    projectId: 'uni-transit-app-4556',
    authDomain: 'uni-transit-app-4556.firebaseapp.com',
    databaseURL: 'https://uni-transit-app-4556-default-rtdb.firebaseio.com',
    storageBucket: 'uni-transit-app-4556.firebasestorage.app',
    measurementId: 'G-7NSZTSPXL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtDuop5mBwGULZ8y-56z199FokoeZ9F6Q',
    appId: '1:413834253790:android:bd10f3529a6bd79129f94f',
    messagingSenderId: '413834253790',
    projectId: 'uni-transit-app-4556',
    databaseURL: 'https://uni-transit-app-4556-default-rtdb.firebaseio.com',
    storageBucket: 'uni-transit-app-4556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQLUf2ZsSLO5oO1XSm24KQ1MdoCOG3SI',
    appId: '1:413834253790:ios:8d7d18086d8b781d29f94f',
    messagingSenderId: '413834253790',
    projectId: 'uni-transit-app-4556',
    databaseURL: 'https://uni-transit-app-4556-default-rtdb.firebaseio.com',
    storageBucket: 'uni-transit-app-4556.firebasestorage.app',
    iosBundleId: 'com.microcode.uniTransit',
  );
}
